"""add notification idempotency key

Revision ID: 0fbb70ca0220
Revises: 743c7cd41b9d
Create Date: 2026-09-15 14:13:11.942594

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fbb70ca0220"
down_revision: str | Sequence[str] | None = "743c7cd41b9d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column(
            "idempotency_key",
            sa.String(length=100),
            nullable=True,
        ),
    )

    op.create_index(
        op.f("ix_notifications_idempotency_key"),
        "notifications",
        ["idempotency_key"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_notifications_idempotency_key"),
        table_name="notifications",
    )
    op.drop_column("notifications", "idempotency_key")
    # ### end Alembic commands ###
